version: '3'

services:
  hfs:
    image: rejetto/hfs:v0.53.0
    volumes:
      - ./hfsconf:/home/hfs/.hfs # for hfs conf persistence
      # don't forget to share volumes to access certificate files
    environment:
      - HFS_PORT=8080 # default is 80
      - HFS_CREATE_ADMIN=password123 # will create the admin user with password "password123" \
    ports:
      - 8080:8080